name: Delete All Releases and Tags

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  delete-releases-and-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-github-cli@v1

      - name: Delete all releases
        run: |
          gh release list --all | awk '{print $1}' | while read -r release; do
            echo "Deleting release: $release"
            gh release delete "$release" -y
          done

      - name: Delete all tags
        run: |
          git fetch --tags
          git tag -l | while read -r tag; do
            echo "Deleting tag: $tag"
            git tag -d "$tag"
            git push --delete origin "$tag"
          done
