name: Check GCC Version

on:
  push:
    branches:
      - main

jobs:
  check-gcc-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check GCC version
      run: gcc --version
