name: Update Checker

env:
  REPO_URL: https://github.com/fw876/helloworld
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 10 5 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
        echo "commitHash=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v3
      with:
        path: .commitHash
        key: HEAD-${{ env.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ env.commitHash }} | tee .commitHash

    - name: Trigger build for specific branches
      if: steps.cacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update
        client-payload: |
          {
            "refs": ["refs/heads/main", "refs/heads/r2s"]
          }

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 10
        keep_minimum_runs: 1
